<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUQfhnCU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUQfhnCU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUQfhnCU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUQfhnCU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUQfhnCU\App_KernelDevDebugContainer([
    'container.build_hash' => 'UQfhnCU',
    'container.build_id' => '17582ffa',
    'container.build_time' => 1576510788,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUQfhnCU');
