<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNVYE4hB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNVYE4hB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNVYE4hB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNVYE4hB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNVYE4hB\App_KernelDevDebugContainer([
    'container.build_hash' => 'NVYE4hB',
    'container.build_id' => '1faef031',
    'container.build_time' => 1576330029,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNVYE4hB');
